### PR TITLE
rename to smirnoff and add changes in smarty pull request

### PR DESCRIPTION
**Pull request by bannanc**
This is the same as pull request [#232 on smarty](https://github.com/open-forcefield-group/smarty/pull/232)

### CODE REVIEW

**Comment by bannanc** [comment]
@davidlmobley 
I didn't change in any of the conda things, I just changed the name of the directory and file. Let me know if I should try to fix the conda part (aka get Nathan to help me with it).

**Comment by davidlmobley** [comment]
@bannanc - please set with Nathan to make sure everything gets moved over to `smirnoff` rather than `smirff` (including package name, stuff in `setup.py`, `conda-recipes/meta.yaml`, etc. (It's not actually in THAT many places so you should be able to do most of it yourself, probably by searching the repo for the word `smirff`!) and then do a new release and push a new build to the conda channel.

I'm OK with it being merged once you guys are ready, and this does not necessarily have to be done all in one PR.

**Comment by bannanc** [comment]
I renamed all instances of smirff to smirnoff, I'm going to merge for now and I'll check with Nathan about how to change the conda channel with the name change

**Comment by davidlmobley** [comment]
> I renamed all instances of smirff to smirnoff, I'm going to merge for now and I'll check with Nathan about how to change the conda channel with the name change

Thanks, @bannanc . Will also need to do a new point release for that via the "releases" tab on GitHub.

**Pull request merged**
